services:
  ChatBot_asr_backend:
    pull_policy: never
    build:
      context: ..
      dockerfile: ./docker/dev.Dockerfile
    image: asr-backend
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=*
      - WHISPER_MODEL=/app/data/whisper/small.pt
      - MEDIA_DIR=/app/data/media
      - NVIDIA_VISIBLE_DEVICES=0
    ports:
      - 8001:8001
    volumes:
      - ./playground/data:/app/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    runtime: nvidia
